networks:
  net:
    name: net
    driver: bridge

services:
    
  sms-api:
    networks:
        - net
    build:
      context: ./
      dockerfile: Dockerfile 
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: ${DATABASE_URL} 
      JWT_SECRET: ${JWT_SECRET}
      PASSWORD_SALT: ${PASSWORD_SALT}
      NODE_ENV: production
    env_file: .env
